# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Koenv/Desktop/week3/week3.srcs/sources_1/Basys-3-Master.xdc

# IP: ip/clockDivider/clockDivider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clockDivider || ORIG_REF_NAME==clockDivider} -quiet] -quiet
